//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_LearningApp.AdminServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Course", Namespace="http://schemas.datacontract.org/2004/07/AdminServices")]
    [System.SerializableAttribute()]
    public partial class Course : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourseCategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourseDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CourseIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourseNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CoursePriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CourseCategory {
            get {
                return this.CourseCategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseCategoryField, value) != true)) {
                    this.CourseCategoryField = value;
                    this.RaisePropertyChanged("CourseCategory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CourseDescription {
            get {
                return this.CourseDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseDescriptionField, value) != true)) {
                    this.CourseDescriptionField = value;
                    this.RaisePropertyChanged("CourseDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CourseID {
            get {
                return this.CourseIDField;
            }
            set {
                if ((this.CourseIDField.Equals(value) != true)) {
                    this.CourseIDField = value;
                    this.RaisePropertyChanged("CourseID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CourseName {
            get {
                return this.CourseNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseNameField, value) != true)) {
                    this.CourseNameField = value;
                    this.RaisePropertyChanged("CourseName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CoursePrice {
            get {
                return this.CoursePriceField;
            }
            set {
                if ((this.CoursePriceField.Equals(value) != true)) {
                    this.CoursePriceField = value;
                    this.RaisePropertyChanged("CoursePrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CourseDetails", Namespace="http://schemas.datacontract.org/2004/07/AdminServices")]
    [System.SerializableAttribute()]
    public partial class CourseDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourseCategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourseDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CourseIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourseNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CoursePriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CourseCategory {
            get {
                return this.CourseCategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseCategoryField, value) != true)) {
                    this.CourseCategoryField = value;
                    this.RaisePropertyChanged("CourseCategory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CourseDescription {
            get {
                return this.CourseDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseDescriptionField, value) != true)) {
                    this.CourseDescriptionField = value;
                    this.RaisePropertyChanged("CourseDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CourseID {
            get {
                return this.CourseIDField;
            }
            set {
                if ((this.CourseIDField.Equals(value) != true)) {
                    this.CourseIDField = value;
                    this.RaisePropertyChanged("CourseID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CourseName {
            get {
                return this.CourseNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseNameField, value) != true)) {
                    this.CourseNameField = value;
                    this.RaisePropertyChanged("CourseName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CoursePrice {
            get {
                return this.CoursePriceField;
            }
            set {
                if ((this.CoursePriceField.Equals(value) != true)) {
                    this.CoursePriceField = value;
                    this.RaisePropertyChanged("CoursePrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdminServices.IAdminService1")]
    public interface IAdminService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService1/AdminSignIn", ReplyAction="http://tempuri.org/IAdminService1/AdminSignInResponse")]
        bool AdminSignIn(string Username, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService1/AdminSignIn", ReplyAction="http://tempuri.org/IAdminService1/AdminSignInResponse")]
        System.Threading.Tasks.Task<bool> AdminSignInAsync(string Username, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService1/AddCourse", ReplyAction="http://tempuri.org/IAdminService1/AddCourseResponse")]
        void AddCourse(string courseName, string courseDescription, int coursePrice, string courseCategory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService1/AddCourse", ReplyAction="http://tempuri.org/IAdminService1/AddCourseResponse")]
        System.Threading.Tasks.Task AddCourseAsync(string courseName, string courseDescription, int coursePrice, string courseCategory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService1/DeleteCourse", ReplyAction="http://tempuri.org/IAdminService1/DeleteCourseResponse")]
        void DeleteCourse(int courseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService1/DeleteCourse", ReplyAction="http://tempuri.org/IAdminService1/DeleteCourseResponse")]
        System.Threading.Tasks.Task DeleteCourseAsync(int courseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService1/EditCourse", ReplyAction="http://tempuri.org/IAdminService1/EditCourseResponse")]
        void EditCourse(int courseId, string courseName, string courseDescription, int coursePrice, string courseCategory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService1/EditCourse", ReplyAction="http://tempuri.org/IAdminService1/EditCourseResponse")]
        System.Threading.Tasks.Task EditCourseAsync(int courseId, string courseName, string courseDescription, int coursePrice, string courseCategory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService1/ViewCourses", ReplyAction="http://tempuri.org/IAdminService1/ViewCoursesResponse")]
        E_LearningApp.AdminServices.Course[] ViewCourses();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService1/ViewCourses", ReplyAction="http://tempuri.org/IAdminService1/ViewCoursesResponse")]
        System.Threading.Tasks.Task<E_LearningApp.AdminServices.Course[]> ViewCoursesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService1/CourseDetails", ReplyAction="http://tempuri.org/IAdminService1/CourseDetailsResponse")]
        E_LearningApp.AdminServices.CourseDetails CourseDetails(string courseName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService1/CourseDetails", ReplyAction="http://tempuri.org/IAdminService1/CourseDetailsResponse")]
        System.Threading.Tasks.Task<E_LearningApp.AdminServices.CourseDetails> CourseDetailsAsync(string courseName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdminService1Channel : E_LearningApp.AdminServices.IAdminService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminService1Client : System.ServiceModel.ClientBase<E_LearningApp.AdminServices.IAdminService1>, E_LearningApp.AdminServices.IAdminService1 {
        
        public AdminService1Client() {
        }
        
        public AdminService1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminService1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminService1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminService1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AdminSignIn(string Username, string Password) {
            return base.Channel.AdminSignIn(Username, Password);
        }
        
        public System.Threading.Tasks.Task<bool> AdminSignInAsync(string Username, string Password) {
            return base.Channel.AdminSignInAsync(Username, Password);
        }
        
        public void AddCourse(string courseName, string courseDescription, int coursePrice, string courseCategory) {
            base.Channel.AddCourse(courseName, courseDescription, coursePrice, courseCategory);
        }
        
        public System.Threading.Tasks.Task AddCourseAsync(string courseName, string courseDescription, int coursePrice, string courseCategory) {
            return base.Channel.AddCourseAsync(courseName, courseDescription, coursePrice, courseCategory);
        }
        
        public void DeleteCourse(int courseId) {
            base.Channel.DeleteCourse(courseId);
        }
        
        public System.Threading.Tasks.Task DeleteCourseAsync(int courseId) {
            return base.Channel.DeleteCourseAsync(courseId);
        }
        
        public void EditCourse(int courseId, string courseName, string courseDescription, int coursePrice, string courseCategory) {
            base.Channel.EditCourse(courseId, courseName, courseDescription, coursePrice, courseCategory);
        }
        
        public System.Threading.Tasks.Task EditCourseAsync(int courseId, string courseName, string courseDescription, int coursePrice, string courseCategory) {
            return base.Channel.EditCourseAsync(courseId, courseName, courseDescription, coursePrice, courseCategory);
        }
        
        public E_LearningApp.AdminServices.Course[] ViewCourses() {
            return base.Channel.ViewCourses();
        }
        
        public System.Threading.Tasks.Task<E_LearningApp.AdminServices.Course[]> ViewCoursesAsync() {
            return base.Channel.ViewCoursesAsync();
        }
        
        public E_LearningApp.AdminServices.CourseDetails CourseDetails(string courseName) {
            return base.Channel.CourseDetails(courseName);
        }
        
        public System.Threading.Tasks.Task<E_LearningApp.AdminServices.CourseDetails> CourseDetailsAsync(string courseName) {
            return base.Channel.CourseDetailsAsync(courseName);
        }
    }
}
